// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDckI9Oic_O0QGwE-QQSkVCujLQkpfZ8Ao',
    appId: '1:875427023176:web:480b0aa6e1fa75bbc50b7d',
    messagingSenderId: '875427023176',
    projectId: 'my-ecommerce-app-82a67',
    authDomain: 'my-ecommerce-app-82a67.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-82a67.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUAhjx8rwWrc-tzgwkcBRtnHXXLLy226Q',
    appId: '1:875427023176:android:d3f6f343edc195c8c50b7d',
    messagingSenderId: '875427023176',
    projectId: 'my-ecommerce-app-82a67',
    storageBucket: 'my-ecommerce-app-82a67.firebasestorage.app',
  );
}
